### ISSUE TITLE
Error when trying to install

### ISSUE THREAD

**Issue by kevinhower** [invoke-ai/invoke-training#99]
I am on an M1 Ultra Mac with 128GB memory and running Ventura (13.6.3). I can run the main InvokeAI that does the image generation but this training code won't let me install it which is super frustrating. Despite having Torch installed in the virtual environment, I get this when trying to run the install command (after it has installed a bunch of other stuff):

 × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [17 lines of output]
      Traceback (most recent call last):
        File "/Volumes/MegacityTwo/invoke-training/venv/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Volumes/MegacityTwo/invoke-training/venv/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Volumes/MegacityTwo/invoke-training/venv/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/private/var/folders/50/7bphw7rj7hx8kpvc733n1tvc0000gn/T/pip-build-env-ba0s8vje/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/private/var/folders/50/7bphw7rj7hx8kpvc733n1tvc0000gn/T/pip-build-env-ba0s8vje/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/50/7bphw7rj7hx8kpvc733n1tvc0000gn/T/pip-build-env-ba0s8vje/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 487, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/private/var/folders/50/7bphw7rj7hx8kpvc733n1tvc0000gn/T/pip-build-env-ba0s8vje/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 23, in <module>
      ModuleNotFoundError: No module named 'torch'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

If I can run Invoke, I should also be able to run the training. I am very confused how, if I have torch already installed, it can't find a module named 'torch'. Makes no sense. I would greatly appreciate your help with this. If it does not yet work on M1 Macs for some reason, it would be super awesome if you could correct that deficiency.  Thanks! :)

**Comment by kevinhower** [comment]
I did the above but it says torch does not exist. I also did the "pip show torch" command you suggested (in the venv) and it gave me this in response to that command:

Name: torch
Version: 2.2.2
Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
Home-page: https://pytorch.org/
Author: PyTorch Team
Author-email: packages@pytorch.org
License: BSD-3
Location: /Volumes/MegacityTwo/invoke-training/venv/lib/python3.10/site-packages
Requires: filelock, fsspec, jinja2, networkx, sympy, typing-extensions
Required-by:

So , it seems to have it but if I enter the command  "which torch" it acts like torch doesn't exist. Really bizarre.

Also, if it doesn't work right now, I really hope that since you guys have the inference/generation part working and it's not super slow, that the training can be updated at some point in the reasonably near future so that it does work on Mac. 

Thanks for your reply :)

**Comment by cgi-joe** [comment]
@kevinhower what version of Python are you using? I had this error and I had to make sure I was using 3.10. (3.10.12 to be specific seems to work)

**Comment by kevinhower** [comment]
I have 3.10.12 as the version in the virtual environment. At least that is what I get with the venv activated and I type python --version

**Comment by kevinhower** [comment]
I give up. I am closing this issue as I have more pressing things in my life.
